package model

enum class Family {
    SCHILTZ,
    MUKENDI,
    PAPA,
    MBAPPE,
    KRADCHI,
    KABUELA,
    SCHILTZ_KP,
    SCHILTZ_MURIELLE,
    SCHILTZ_THOMAS,
    SAPO_TCHABA,
    SIMBA,
    FRITZ,
    PAPA_FRITZ,
    BERTHIER,
    SAPO_TCHABA_BERTHIER,
    MADENSPACHER,
    SAPO_TCHABA_MADENSPACHER,
    ARNOUX,
    SAPO_TCHABA_ARNOUX,
    MBIYA,
    SENE
}
